name: pr-validation-ef
on:
   pull_request:
     types:
       -  opened
       - synchronize
   push:
    branches:
      - develop
jobs:
     pr-validation-job:
      runs-on: ubuntu-latest
      steps:
        - name: welcom steps
          run: echo "Welcom to github actions" 
